<?php

/**
 * PrepareBoardImages
 *
 * PURPOSE
 * -------
 * Generates the deterministic "slide" node stored inside a Board entry.
 * The Media board front-end is intentionally "dumb":
 *   - It NEVER recomputes SLT.
 *   - It ONLY compares epoch seconds (UTC) against from_ts / until_ts.
 *   - It displays an image when:
 *         now >= from_ts   AND   now < until_ts
 *     (from inclusive, until exclusive).
 *
 *
 * TIME MODEL (SLT-FIRST ARCHITECTURE)
 * ------------------------------------
 * - Events are authored in SLT (Second Life Time), i.e. America/Los_Angeles.
 * - Each event stores:
 *       "date"       = "YYYY-MM-DD"   (SLT calendar date)
 *       "start_time" = "HH:MM"        (SLT clock time)
 *
 * - Buckets are derived from SLT month:
 *       Class = "EventYYYYMM"   (YYYYMM based on SLT date)
 *
 * - Therefore:
 *     (1) Month scanning MUST use SLT calendar (America/Los_Angeles).
 *     (2) start_ts MUST be computed by parsing date+start_time in SLT timezone.
 *
 * - All timestamps written in "slide" are UNIX epoch seconds (UTC).
 *   The front-end only compares epoch numbers.
 *
 *
 * DISPLAY WINDOW LOGIC
 * --------------------
 * For each event:
 *
 *     start_ts  = SLT date+time interpreted in America/Los_Angeles
 *     from_ts   = start_ts - (days_ahead * 86400)
 *     until_ts  = start_ts + (show_mins_after_start * 60)
 *
 * Meaning:
 *   - days_ahead controls how many days BEFORE the event
 *     the image becomes eligible for display.
 *
 *   - show_mins_after_start controls how many minutes AFTER
 *     the event start the image remains visible.
 *
 * Example:
 *   days_ahead = 7
 *   show_mins_after_start = 0
 *
 *   → Image becomes visible 7 days before the event.
 *   → Image disappears exactly at event start.
 *
 *
 * IMPORTANT: SCAN HORIZON VS DISPLAY WINDOW
 * ------------------------------------------
 * - days_ahead ONLY controls the display window (from_ts).
 * - It does NOT limit which events are loaded into slide.items.
 *
 * - The function scans multiple future months (scan_months_ahead)
 *   so that all upcoming events are already present in slide.items.
 *
 * This ensures:
 *   - The board does NOT require a backend refresh
 *     at the exact moment an event becomes visible.
 *   - The front-end auto-activates images
 *     solely by comparing now against from_ts/until_ts.
 *
 *
 * DATABASE STRUCTURE (CURRENT SYSTEM)
 * ====================================
 *
 * 1) BOARD STORAGE (NV "List")
 * -----------------------------
 *   Class : "Board"
 *   Name  : <board_id>
 *
 *   JSON example:
 *   {
 *     "last_hooked": 1770914697,
 *     "project_id": "fec9049a-fc43-45ee-a28a-d7ae04a69688",
 *
 *     "config": {
 *       "all_artists": true,
 *       "artists": [],
 *       "all_venues": true,
 *       "venues": [],
 *
 *       "days_ahead": 7,
 *       "show_mins_after_start": 0,
 *       "seconds_shown": 10,
 *
 *       "scan_months_ahead": 24     // optional, default if absent
 *     },
 *
 *     "slide": { ... }              // generated by this function
 *   }
 *
 *
 * 2) EVENTS STORAGE (NV "SessionList")
 * -------------------------------------
 *   SessionID : <project_id>
 *   Class     : "EventYYYYMM"  (based on SLT month)
 *   Name      : <event_id>
 *
 *   JSON example:
 *   {
 *     "name": "Friday night party",
 *     "artist_id": "<uuid>",
 *     "venue_id": "<uuid>",
 *     "date": "2026-02-13",       // SLT date
 *     "start_time": "18:00",      // SLT time
 *     "end_time": "19:00",
 *     "picture_id": "<file_id>",
 *     "created_at": 1770988925,
 *     "created_by": "<uuid>"
 *   }
 *
 *
 * OUTPUT STRUCTURE (stored under Board["slide"])
 * ===============================================
 *
 * {
 *   "prepared_at": <epoch UTC>,   // when slide was generated
 *   "start_at":    <epoch UTC>,   // anchor used for slideshow slot sync
 *   "step_sec":    <int>,         // seconds per image (rotation speed)
 *
 *   "items": [
 *     {
 *       "image_id": "<file_id>",
 *       "from_ts":  <epoch UTC>,
 *       "until_ts": <epoch UTC>,
 *       "start_ts": <epoch UTC>   // event start, used for ordering/debug
 *     },
 *     ...
 *   ]
 * }
 *
 *
 * FRONT-END CONTRACT
 * -------------------
 * - The board:
 *     • builds an "active playlist" where:
 *         now >= from_ts AND now < until_ts
 *     • rotates inside that playlist using:
 *         start_at + step_sec (slot alignment)
 *
 * - start_ts is NOT required for filtering on the front-end.
 *   It is included only for deterministic ordering and debugging.
 *
 *
 * @param string $boardId
 * @return bool
 */

function PrepareBoardImages(string $boardId): bool
{
    // -------------------------------------------------------------------------
    // STEP 1) Load and validate Board JSON
    // -------------------------------------------------------------------------
    $boardJson = NVGetList("Board", $boardId);
    if (!is_string($boardJson) || $boardJson === "") return false;

    $board = json_decode($boardJson, true);
    if (json_last_error() !== JSON_ERROR_NONE || !is_array($board)) return false;

    $projectId = trim((string)($board["project_id"] ?? ""));
    if ($projectId === "") return false;

    // -------------------------------------------------------------------------
    // STEP 2) Read config with defaults
    // -------------------------------------------------------------------------
    $cfg = (isset($board["config"]) && is_array($board["config"])) ? $board["config"] : [];

    $allArtists = (bool)($cfg["all_artists"] ?? true);
    $artists    = (is_array($cfg["artists"] ?? null)) ? $cfg["artists"] : [];

    $allVenues  = (bool)($cfg["all_venues"] ?? true);
    $venues     = (is_array($cfg["venues"] ?? null)) ? $cfg["venues"] : [];

    // Display window (front-end filtering):
    // - days_ahead controls "how many days before start_ts the image becomes active".
    $daysAhead  = (int)($cfg["days_ahead"] ?? 7);
    if ($daysAhead < 0) $daysAhead = 0;

    $minsAfterStart = (int)($cfg["show_mins_after_start"] ?? 0);
    if ($minsAfterStart < 0) $minsAfterStart = 0;

    $stepSec = (int)($cfg["seconds_shown"] ?? 10);
    if ($stepSec < 1) $stepSec = 10;

    // IMPORTANT: scan horizon must be decoupled from display window.
    // If we only scan "days_ahead", future events would never be present in slide.items
    // unless someone triggers PrepareBoardImages again in the meantime.
    //
    // Default: scan next 24 months. You can make this a config field later.
    $scanMonthsAhead = (int)($cfg["scan_months_ahead"] ?? 24);
    if ($scanMonthsAhead < 1) $scanMonthsAhead = 1;
    if ($scanMonthsAhead > 120) $scanMonthsAhead = 120; // safety (10 years)

    // Build allow-lists
    $artistAllow = [];
    if (!$allArtists) {
        foreach ($artists as $a) {
            if (!is_string($a)) continue;
            $a = trim($a);
            if ($a !== "") $artistAllow[$a] = true;
        }
    }

    $venueAllow = [];
    if (!$allVenues) {
        foreach ($venues as $v) {
            if (!is_string($v)) continue;
            $v = trim($v);
            if ($v !== "") $venueAllow[$v] = true;
        }
    }

    // -------------------------------------------------------------------------
    // STEP 3) Determine scan horizon (months to read) using SLT calendar
    // -------------------------------------------------------------------------
    $now = time();

    $tzSLT = new DateTimeZone("America/Los_Angeles");

    $dtStart = (new DateTimeImmutable("@$now"))->setTimezone($tzSLT);

    // Scan end = start month + scanMonthsAhead
    $dtEndMonth = $dtStart
        ->setDate((int)$dtStart->format("Y"), (int)$dtStart->format("m"), 1)
        ->setTime(0, 0, 0)
        ->modify("+" . $scanMonthsAhead . " month");

    // Cursor at first day of current SLT month
    $dtCursor = $dtStart
        ->setDate((int)$dtStart->format("Y"), (int)$dtStart->format("m"), 1)
        ->setTime(0, 0, 0);

    // -------------------------------------------------------------------------
    // STEP 4) Enumerate candidate events from NV buckets (EventYYYYMM)
    // -------------------------------------------------------------------------
    $items = [];

    while ($dtCursor <= $dtEndMonth) {

        $yyyymm = $dtCursor->format("Ym");   // e.g. "202602" in SLT calendar
        $class  = "Event" . $yyyymm;

        $eventIds = NVGetSessionLists($projectId, $class);
        if (is_array($eventIds) && count($eventIds) > 0) {

            foreach ($eventIds as $eventId) {

                if (!is_string($eventId) || $eventId === "") continue;

                $evJson = NVGetSessionList($projectId, $class, $eventId);
                if (!is_string($evJson) || $evJson === "") continue;

                $ev = json_decode($evJson, true);
                if (json_last_error() !== JSON_ERROR_NONE || !is_array($ev)) continue;

                $imageId = trim((string)($ev["picture_id"] ?? ""));
                if ($imageId === "") continue;

                $artistId = trim((string)($ev["artist_id"] ?? ""));
                if (!$allArtists && $artistId !== "" && !isset($artistAllow[$artistId])) continue;

                $venueId = trim((string)($ev["venue_id"] ?? ""));
                if (!$allVenues && $venueId !== "" && !isset($venueAllow[$venueId])) continue;

                $date = trim((string)($ev["date"] ?? ""));
                if ($date === "") continue;

                $startTime = trim((string)($ev["start_time"] ?? ""));
                if ($startTime === "") $startTime = "00:00";

                if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $date)) continue;
                if (!preg_match('/^\d{2}:\d{2}(:\d{2})?$/', $startTime)) continue;

                // SLT-first: interpret event start in America/Los_Angeles then to epoch.
                $dtStr = $date . " " . substr($startTime, 0, 5) . ":00";
                $dtEv = DateTimeImmutable::createFromFormat("Y-m-d H:i:s", $dtStr, $tzSLT);
                if (!$dtEv) continue;

                $startTs = (int)$dtEv->getTimestamp();

                // Compute the display window in epoch seconds:
                // - from_ts  inclusive
                // - until_ts exclusive (board uses now < until_ts)
                $fromTs  = $startTs - ($daysAhead * 86400);
                $untilTs = $startTs + ($minsAfterStart * 60);

                // Optional cleanup: if the item is fully expired, skip it.
                // This keeps slide.items smaller while remaining correct.
                if ($untilTs > 0 && $untilTs <= $now) continue;

                $items[] = [
                    "image_id" => $imageId,
                    "from_ts"  => $fromTs,
                    "until_ts" => $untilTs,
                    "start_ts" => $startTs, // ordering/debug only (front-end can ignore)
                ];
            }
        }

        $dtCursor = $dtCursor->modify("+1 month");
    }

    // -------------------------------------------------------------------------
    // STEP 5) Sort deterministically (start_ts ASC, tie-breaker image_id ASC)
    // -------------------------------------------------------------------------
    usort($items, function ($a, $b) {
        $sa = (int)($a["start_ts"] ?? 0);
        $sb = (int)($b["start_ts"] ?? 0);
        if ($sa !== $sb) return $sa <=> $sb;

        $ia = (string)($a["image_id"] ?? "");
        $ib = (string)($b["image_id"] ?? "");
        return strcmp($ia, $ib);
    });

    // -------------------------------------------------------------------------
    // STEP 6) Build slide node
    // -------------------------------------------------------------------------
    $preparedAt = time();
    $startAt = $preparedAt - ($preparedAt % $stepSec);

    $slide = [
        "prepared_at" => $preparedAt,
        "start_at"    => $startAt,
        "step_sec"    => $stepSec,
        "items"       => $items,
    ];

    // -------------------------------------------------------------------------
    // STEP 7) Persist slide into Board JSON
    // -------------------------------------------------------------------------
    $board["slide"] = $slide;

    NVSetList(
        "Board",
        $boardId,
        json_encode($board, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)
    );

    return true;
}